x-db: &db
  image: 'plyo/postgres:database-13.1-6.0.2'
  environment:
    - APP_PASSWORD=password
    - ADMIN_PASSWORD=password
    - POSTGRES_PASSWORD=password
    - DB_NAME=test_db
    - SCHEMA_NAME=test_schema

version: '3.4'
services:
  backups:
    build: .
    environment:
      # DB to dump
      DB_NAME: test_db

      # DBs to dump
      DB_CONFIG_1: db-1:5432:*:postgres:password
      DB_CONFIG_2: db-2:5432:*:postgres:password

      # This dir will be created if it doesn't exist. This must be writable by the user the script is
      # running as.
      BACKUP_DIR: /backups/

      # SETTINGS FOR ROTATED BACKUPS

      # Which day to take the weekly backup from (1-7 = Monday-Sunday)
      DAY_OF_WEEK_TO_KEEP: 5

      # Number of hours to keep daily backups
      DAYS_TO_KEEP_HOURLY: 1

      # Number of days to keep daily backups
      DAYS_TO_KEEP_DAILY: 7

      # How many weeks to keep weekly backups
      WEEKS_TO_KEEP_WEEKLY: 4

      # How many months to keep monthly backups
      MONTHS_TO_KEEP_MONTHLY: 6

      # Avoid dumping of existent roles to prevent password rewriting
      IGNORE_DUMP_ROLES: \(admin\|app\|postgres\)

      PERFORM_BACKUP_ROLES: "1"

      S3_KEY: '*'
      S3_SECRET_KEY: '*'
      S3_BUCKET: plyo-db-backups-prod
      S3_BUCKET_URL: https://fra1.digitaloceanspaces.com
    volumes:
      - ./backups/:/backups/
      - ./src:/usr/src/app/
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    depends_on:
      - db-1
      - db-2

  db-1:
    <<: *db

  db-2:
    <<: *db
