x-db: &db
  image: 'plyo/postgres:database-13.1-6.0.2'
  environment:
    - APP_PASSWORD=password
    - ADMIN_PASSWORD=password
    - POSTGRES_PASSWORD=password
    - DB_NAME=test_db
    - SCHEMA_NAME=test_schema

version: '3.4'
services:
  backups:
    build: .
    env_file:
      - .env
    volumes:
      - ./backups/:/backups/
      - ./src:/usr/src/app/
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    depends_on:
      - db-1
      - db-2

  db-1:
    <<: *db

  db-2:
    <<: *db
