backups:
  build: .
  environment:
    # Google drive settings
    - ACCESS_TOKEN=$GDRIVE_ACCESS_TOKEN
    - CLIENT_ID=$GDRIVE_CLIENT_ID
    - CLIENT_SECRET=$GDRIVE_CLIENT_SECRET
    - EXPIRY_DATE=$GDRIVE_EXPIRY_DATE
    - REFRESH_TOKEN=$GDRIVE_REFRESH_TOKEN

    # DBs to dump
    - DB_CONFIG_1=postgres-1:5432:*:postgres:password
    - DB_CONFIG_2=postgres-2:5432:*:postgres:password

    # This dir will be created if it doesn't exist.  This must be writable by the user the script is
    # running as.
    - BACKUP_DIR=/backups/

    - INCLUDE_SCHEMA_LIST='plyo'

    # SETTINGS FOR ROTATED BACKUPS

    # Which day to take the weekly backup from (1-7 = Monday-Sunday)
    - DAY_OF_WEEK_TO_KEEP=5

    # Number of days to keep daily backups
    - DAYS_TO_KEEP=7

    # How many weeks to keep weekly backups
    - WEEKS_TO_KEEP=5

    # Run backups at 3am each night
    # -CRON_PERIOD=0 3 * * *

    # Run backups every minute for tests
    - CRON_PERIOD=* * * * *

    - GDRIVE_UPLOAD_DIR=dev-backups
  volumes:
    - './backups/:/backups/'
  links:
    - postgres-1
    - postgres-2
postgres-1:
  image: 'plyo/postgres'
  environment:
    - APP_PASS=password
    - PLYO_PASS=password
    - POSTGRES_PASSWORD=password
postgres-2:
  image: 'plyo/postgres'
  environment:
    - APP_PASS=password
    - PLYO_PASS=password
    - POSTGRES_PASSWORD=password
