x-db_defaults: &db_defaults
  environment:
    - POSTGRES_PASSWORD=password
    - ADMIN_ROLE_NAME=admin
    - APP_ROLE_NAME=app
    - ADMIN_PASSWORD=password
    - APP_PASSWORD=password
    - DB_NAME=test_db
    - SCHEMA_NAME=test_schema
    - PRIVATE_SCHEMA_NAME=test_schema_private
    - EXTENSIONS=pgcrypto,ltree
#  ports:
#    - '5432:5432'

version: '3.4'
services:
  db:
    build:
      context: .
      target: db
    volumes:
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - '.:/app'
    <<: *db_defaults

  test:
    build:
      context: .
      target: test
    <<: *db_defaults
    volumes:
      - './docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
      - '.:/app'

  test-ci:
    build:
      context: .
      target: test
    <<: *db_defaults
