version: '3.4'
services:
  sanitizer:
    build:
      context: .
    working_dir: /usr/src/app
    env_file:
      - .env
    volumes:
      - ./src/start.sh:/usr/src/app/start.sh
      - ./src/mount-s3.sh:/usr/src/app/mount-s3.sh
      - ./sql:/usr/src/app/sql
      - ./files:/files
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
