version: '2'
services:
  publisher:
    build: .
    working_dir: /usr/src/app
    environment:
      - DOCKERHUB_LOGIN
      - DOCKERHUB_PASS
      - APP_PASS=password
      - ADMIN_PASS=password
      - POSTGRES_PASS=password
      - DUMP_NAME_SUFFIX=-preview-db.prod-dbs.default.plyo.in-5434-hourly.backup
      - POSTGRES_IMAGE=plyo/postgres:9.5.10-1.0.1
      - DUMPS_DIR
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
