version: '3.4'
services:
  publisher:
    build: .
    working_dir: /usr/src/app
    environment:
      - DOCKERHUB_LOGIN
      - DOCKERHUB_PASS
      - APP_PASS=password
      - ADMIN_PASS=password
      - POSTGRES_PASS=password
      - DUMP_NAME_SUFFIX=-prod-db-5432-hourly.backup
      - POSTGRES_IMAGE=plyo/postgres:database
      - DUMPS_DIR
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
