version: '2'
services:
  publisher:
    build: .
    working_dir: /usr/src/app
    environment:
      - DOCKERHUB_LOGIN
      - DOCKERHUB_PASS
      - APP_PASS=password
      - PLYO_PASS=password
      - POSTGRES_PASS=password
      - DUMPS_DIR
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
