version: '3.4'
services:
  publisher:
    build: .
    working_dir: /usr/src/app
    environment:
      - DB_NAME=test_db
      - DOCKERHUB_LOGIN
      - DOCKERHUB_PASS
      - DUMP_NAME_SUFFIX=-prod-db-5432-hourly.backup
      - POSTGRES_IMAGE=plyo/postgres:database-10.4-4.1.0
      - DUMPS_DIR
      - DESTINATION_DOCKER_IMAGE=plyo/db:data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./start.sh:/usr/src/app/start.sh
