name: CI Release

on:
  push:
    tags:
      - 'database-*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3
      - name: Setup docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1.0.9
        with:
          version: '1.19.0'
      - name: Running tests
        working-directory: database
        run: |
          docker-compose up test-ci
          
          for i in `seq 1 300`; # waiting 5 mins since building postgres first time can take significant time
          do
            docker-compose exec test-ci psql --username postgres -c "\t" && echo DB Up && exit 0
            echo -n .
            sleep 1
          done
          
          docker-compose exec test-ci make test

  publish:
    runs-on: ubuntu-latest
    needs: [ test ]
    name: Publish
    steps:
      - uses: actions/checkout@v3
      - name: Create Docker tag
        id: create_tag
        uses: InfraWay/gh-create-docker-tag@v3.3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        run: |
          IFS=- read service mics <<< ${GITHUB_REF_NAME}
          cd ${service}
          docker build -t ${{ steps.create_tag.outputs.name }} .
          docker push ${{ steps.create_tag.outputs.name }}
