name: Sanitizer Release

on:
  push:
    tags:
      - 'sanitizer-*'

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 13.1, 14.1 ]
    name: Publish
    steps:
      - uses: actions/checkout@v3
      - name: Create Docker tag
        id: create_tag
        uses: InfraWay/gh-create-docker-tag@v3.3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        run: |
          IFS=- read service mics <<< ${GITHUB_REF_NAME}
          cd ${service}
          docker build --build-arg="version=${{ matrix.version }}" -t ${{ steps.create_tag.outputs.name }}-${{ matrix.version }} .
          docker push ${{ steps.create_tag.outputs.name }}-${{ matrix.version }}
