name: CI Release

on:
  push:
    tags:
      - 'backups-*'
      - 'publisher-*'

jobs:
  publish:
    name: Publish
    steps:
      - uses: actions/checkout@v3
      - name: Create Docker tag
        id: create_tag
        uses: InfraWay/gh-create-docker-tag@v3.3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push docker image
        run: |
          IFS=- read service mics <<< ${GITHUB_REF_NAME}
          cd ${service}
          docker build -t ${{ steps.create_tag.outputs.name }} .
          docker push ${{ steps.create_tag.outputs.name }}
